### ISSUE TITLE
TypeError: 'bool' object is not callable - indexer.index_metadata

### ISSUE THREAD

**Issue by eahorwath** [HBClab/NiBetaSeries#343]
Hi,

I am trying to run nibetaseries version 0.6.0 with the following code: 

`nibs \
    -c white_matter dvars framewise_displacement trans_x trans_y trans_z rot_x rot_y rot_z \
    --participant-label 02 \
    --estimator lss \
    --hrf-model 'spm' \
    -w /Volumes/shared/Psychology/Murty_Group/studies/ddmsq.01/data/bids2/derivatives/work \
    /Volumes/shared/Psychology/Murty_Group/studies/ddmsq.01/data/bids2 \
    fmriprep \
    /Volumes/shared/Psychology/Murty_Group/studies/ddmsq.01/data/bids2/derivatives \
    participant `

and I receive this error:

`Traceback (most recent call last):
  File "/Users/tug84242/opt/anaconda3/envs/nibeta/bin/nibs", line 8, in <module>
    sys.exit(main())
  File "/Users/tug84242/opt/anaconda3/envs/nibeta/lib/python3.10/site-packages/nibetaseries/cli/run.py", line 259, in main
    nibetaseries_participant_wf = init_nibetaseries_participant_wf(
  File "/Users/tug84242/opt/anaconda3/envs/nibeta/lib/python3.10/site-packages/nibetaseries/workflows/base.py", line 150, in init_nibetaseries_participant_wf
    indexer.index_metadata(**metadata_filter)
TypeError: 'bool' object is not callable`

I'm not sure if this is helpful, but I also see the following warning which looks related to this error, although from looking at the source code, I believe the recommendation is already how the 'index_metadata' argument is being used:

`/Users/tug84242/opt/anaconda3/envs/nibeta/lib/python3.10/site-packages/bids/layout/validation.py:51: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "`

My file structure containing BIDS and preprocessed data looks like the following:

/Volumes/shared/Psychology/Murty_Group/studies/ddmsq.01/data/bids2/
├── T1w.json
├── dataset_description.json
├── derivatives
│   └── fmriprep
│       ├── dataset_description.json
│       └── sub-02
│           ├── anat
│           │   ├── sub-02_desc-brain_mask.json
│           │   ├── sub-02_desc-brain_mask.nii.gz
│           │   ├── sub-02_desc-preproc_T1w.json
│           │   ├── sub-02_desc-preproc_T1w.nii.gz
│           │   ├── sub-02_dseg.nii.gz
│           │   ├── sub-02_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
│           │   ├── sub-02_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
│           │   ├── sub-02_label-CSF_probseg.nii.gz
│           │   ├── sub-02_label-GM_probseg.nii.gz
│           │   ├── sub-02_label-WM_probseg.nii.gz
│           │   ├── sub-02_space-MNI152NLin2009cAsym_desc-brain_mask.json
│           │   ├── sub-02_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
│           │   ├── sub-02_space-MNI152NLin2009cAsym_desc-preproc_T1w.json
│           │   ├── sub-02_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
│           │   ├── sub-02_space-MNI152NLin2009cAsym_dseg.nii.gz
│           │   ├── sub-02_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
│           │   ├── sub-02_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
│           │   └── sub-02_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz
│           ├── figures
│           │   ├── sub-02_desc-about_T1w.html
│           │   ├── sub-02_desc-conform_T1w.html
│           │   ├── sub-02_desc-summary_T1w.html
│           │   ├── sub-02_dseg.svg
│           │   ├── sub-02_space-MNI152NLin2009cAsym_T1w.svg
│           │   ├── sub-02_task-dict_run-01_desc-carpetplot_bold.svg
│           │   ├── sub-02_task-dict_run-01_desc-compcorvar_bold.svg
│           │   ├── sub-02_task-dict_run-01_desc-confoundcorr_bold.svg
│           │   ├── sub-02_task-dict_run-01_desc-flirtbbr_bold.svg
│           │   ├── sub-02_task-dict_run-01_desc-rois_bold.svg
│           │   ├── sub-02_task-dict_run-01_desc-summary_bold.html
│           │   └── sub-02_task-dict_run-01_desc-validation_bold.html
│           ├── func
│           │   ├── sub-02_task-dict_run-01_desc-confounds_timeseries.json
│           │   ├── sub-02_task-dict_run-01_desc-confounds_timeseries.tsv
│           │   ├── sub-02_task-dict_run-01_from-T1w_to-scanner_mode-image_xfm.txt
│           │   ├── sub-02_task-dict_run-01_from-scanner_to-T1w_mode-image_xfm.txt
│           │   ├── sub-02_task-dict_run-01_space-MNI152NLin2009cAsym_boldref.nii.gz
│           │   ├── sub-02_task-dict_run-01_space-MNI152NLin2009cAsym_desc-brain_mask.json
│           │   ├── sub-02_task-dict_run-01_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
│           │   ├── sub-02_task-dict_run-01_space-MNI152NLin2009cAsym_desc-preproc_bold.json
│           │   └── sub-02_task-dict_run-01_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
│           └── log
│               └── 20221006-162536_efa5b8b6-503d-4291-ae46-88be1652c2a5
│                   └── fmriprep.toml
├── sub-02
│   ├── anat
│   │   └── sub-02_T1w.nii.gz
│   └── func
│       ├── sub-02_task-dict_run-01_bold.nii.gz
│       └── sub-02_task-dict_run-01_events.tsv
└── task-dict_run-01_bold.json

I'm happy to supply any additional information as needed. Thank you in advance for any help!

**Comment by eahorwath** [comment]
For anyone else who may come across this issue, I installed nibetaseries through a Python 3.9 environment, but reverting back to 3.7 resolved the problem.
